# Generated by Django 5.0 on 2026-04-26 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('group', models.CharField(db_index=True, max_length=50, verbose_name='配置分组')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_app.personnel', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置列表',
                'ordering': ['group', 'key'],
            },
        ),
    ]
