# Generated by Django 5.0 on 2026-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(help_text='学员唯一标识符', primary_key=True, serialize=False, verbose_name='学员ID')),
                ('name', models.CharField(help_text='请输入学员的法定姓名', max_length=100, verbose_name='姓名')),
                ('id_card', models.CharField(help_text='请输入18位身份证号，格式为18位数字或末位为X', max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone', models.CharField(help_text='请输入学员的手机号码', max_length=20, verbose_name='手机号码')),
                ('province', models.CharField(blank=True, help_text='请选择或输入省份/直辖市', max_length=50, verbose_name='省份/直辖市')),
                ('city', models.CharField(blank=True, help_text='请选择或输入城市/地级市', max_length=50, verbose_name='城市/地级市')),
                ('district', models.CharField(blank=True, help_text='请选择或输入区/县', max_length=50, verbose_name='区/县')),
                ('detail_address', models.CharField(blank=True, help_text='请输入详细地址，如街道、门牌号', max_length=255, verbose_name='详细地址')),
                ('photo_url', models.URLField(blank=True, help_text='学员证件照的访问地址', max_length=500, verbose_name='照片URL')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员列表',
                'ordering': ['name'],
            },
        ),
    ]
