# Generated by Django 5.0 on 2026-04-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
        ('workflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='操作动作')),
                ('before_state', models.JSONField(blank=True, null=True, verbose_name='变更前状态')),
                ('after_state', models.JSONField(blank=True, null=True, verbose_name='变更后状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_app.personnel', verbose_name='操作人员')),
                ('process_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_app.processinstance', verbose_name='流程实例')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志列表',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_app_a_action_89d7e5_idx'), models.Index(fields=['operator', 'created_at'], name='audit_app_a_operato_17615e_idx'), models.Index(fields=['-created_at'], name='audit_app_a_created_026ff4_idx')],
            },
        ),
    ]
