# Generated by Django 5.0 on 2026-04-23 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='流程实例唯一标识符', primary_key=True, serialize=False, verbose_name='流程实例ID')),
                ('process_key', models.CharField(db_index=True, help_text='流程定义标识，如"training_class_flow"', max_length=100, verbose_name='流程定义Key')),
                ('process_name', models.CharField(help_text='流程实例显示名称', max_length=200, verbose_name='流程名称')),
                ('bpmn_file', models.CharField(help_text='关联的BPMN流程文件路径', max_length=255, verbose_name='BPMN文件路径')),
                ('status', models.CharField(choices=[('running', '运行中'), ('suspended', '已挂起'), ('completed', '已完成'), ('terminated', '已终止')], db_index=True, default='running', help_text='running=运行中, suspended=已挂起, completed=已完成, terminated=已终止', max_length=20, verbose_name='流程状态')),
                ('current_task_id', models.CharField(blank=True, help_text='当前执行的任务节点ID', max_length=100, verbose_name='当前任务ID')),
                ('current_task_name', models.CharField(blank=True, help_text='当前执行的任务节点名称', max_length=200, verbose_name='当前任务名称')),
                ('variables', models.JSONField(default=dict, help_text='存储流程执行过程中的变量数据（JSON格式）', verbose_name='流程变量')),
                ('related_object_type', models.CharField(blank=True, help_text='关联的业务对象类型，如 TrainingClass、Student', max_length=100, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, help_text='关联的业务对象ID', max_length=100, verbose_name='关联对象ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='流程启动时间', verbose_name='启动时间')),
                ('completed_at', models.DateTimeField(blank=True, help_text='流程完成时间', null=True, verbose_name='完成时间')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='流程挂起时间', null=True, verbose_name='挂起时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间', verbose_name='更新时间')),
                ('initiator', models.ForeignKey(blank=True, help_text='启动该流程的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_processes', to='organization_app.personnel', verbose_name='发起人')),
            ],
            options={
                'verbose_name': '流程实例',
                'verbose_name_plural': '流程实例列表',
                'db_table': 'process_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='任务唯一标识符', primary_key=True, serialize=False, verbose_name='任务ID')),
                ('task_id', models.CharField(help_text='BPMN中的任务节点ID', max_length=100, verbose_name='任务节点ID')),
                ('task_name', models.CharField(help_text='任务节点名称', max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消'), ('rejected', '已拒绝')], db_index=True, default='pending', help_text='pending=待处理, in_progress=处理中, completed=已完成, cancelled=已取消, rejected=已拒绝', max_length=20, verbose_name='任务状态')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='任务提交的表单数据（JSON格式）', verbose_name='表单数据')),
                ('comment', models.TextField(blank=True, help_text='任务处理时的意见说明', verbose_name='处理意见')),
                ('started_at', models.DateTimeField(blank=True, help_text='任务开始处理时间', null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, help_text='任务完成时间', null=True, verbose_name='完成时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间', verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, help_text='任务当前办理人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='organization_app.personnel', verbose_name='办理人')),
                ('process_instance', models.ForeignKey(help_text='所属的流程实例', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow_app.processinstance', verbose_name='所属流程实例')),
            ],
            options={
                'verbose_name': '流程任务',
                'verbose_name_plural': '流程任务列表',
                'db_table': 'process_task',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['process_key', 'status'], name='process_ins_process_78a129_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['initiator', 'status'], name='process_ins_initiat_81a21e_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='process_ins_related_6d96a3_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['status', '-started_at'], name='process_ins_status_47c5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['-started_at'], name='process_ins_started_959fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='processtask',
            index=models.Index(fields=['process_instance', 'status'], name='process_tas_process_2bfdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='processtask',
            index=models.Index(fields=['assignee', 'status'], name='process_tas_assigne_370114_idx'),
        ),
        migrations.AddIndex(
            model_name='processtask',
            index=models.Index(fields=['task_id'], name='process_tas_task_id_a73aa6_idx'),
        ),
    ]
