# Generated by Django 5.0 on 2026-04-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(help_text='培训类型唯一标识符', primary_key=True, serialize=False, verbose_name='培训类型ID')),
                ('name', models.CharField(help_text='请输入培训类型名称，如"船员基本安全培训"', max_length=50, verbose_name='培训类型名称')),
                ('category', models.CharField(help_text='岗位/职务分类，如"驾驶岗位"、"轮机岗位"', max_length=20, verbose_name='分类')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='自动更新', verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, help_text='选择上级培训类型，支持多级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='training_app.trainingtype', verbose_name='上级类型')),
            ],
            options={
                'verbose_name': '培训类型',
                'verbose_name_plural': '培训类型列表',
                'ordering': ['category', 'name'],
            },
        ),
    ]
