# Generated by Django 5.0 on 2026-04-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0001_initial'),
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(help_text='培训班唯一标识符', primary_key=True, serialize=False, verbose_name='班级ID')),
                ('class_no', models.CharField(db_index=True, help_text='请输入唯一的班级编号', max_length=32, unique=True, verbose_name='班级编号')),
                ('maritime_system_no', models.CharField(blank=True, help_text='海事局系统编号，允许为空，但不允许重复', max_length=64, verbose_name='海事局系统编号')),
                ('start_date', models.DateField(help_text='请选择培训班开始日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='请选择培训班结束日期', verbose_name='结束日期')),
                ('total_days', models.PositiveIntegerField(default=1, help_text='自动计算：结束日期 - 开始日期 + 1', verbose_name='总天数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('in_progress', '进行中'), ('completed', '已完成'), ('archived', '已归档')], db_index=True, default='draft', help_text='班级当前状态，状态流转由工作流引擎驱动', max_length=20, verbose_name='状态')),
                ('required_attendance_rate', models.DecimalField(decimal_places=2, default=90.0, help_text='最低出勤率要求，范围 0.00 ~ 999.99，单位：%', max_digits=5, verbose_name='必需出勤率')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='自动更新', verbose_name='更新时间')),
                ('checkin_enabled', models.BooleanField(default=False, help_text='是否启用扫码签到功能', verbose_name='启用签到')),
                ('require_location', models.BooleanField(default=False, help_text='是否要求在指定位置范围内签到', verbose_name='要求位置签到')),
                ('location_radius', models.IntegerField(default=200, help_text='允许签到的范围半径，单位：米', verbose_name='签到半径')),
                ('training_location_lat', models.DecimalField(blank=True, decimal_places=7, help_text='培训地点纬度坐标，精度约 0.01米', max_digits=10, null=True, verbose_name='培训地点纬度')),
                ('training_location_lng', models.DecimalField(blank=True, decimal_places=7, help_text='培训地点经度坐标，精度约 0.01米', max_digits=10, null=True, verbose_name='培训地点经度')),
                ('created_by', models.ForeignKey(blank=True, help_text='自动记录', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_app.personnel', verbose_name='创建人')),
                ('training_type', models.ForeignKey(help_text='选择培训班对应的培训类型', on_delete=django.db.models.deletion.PROTECT, to='training_app.trainingtype', verbose_name='培训类型')),
            ],
            options={
                'verbose_name': '培训班',
                'verbose_name_plural': '培训班列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
