# Generated by Django 5.0 on 2026-04-23 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
        ('training_app', '0002_trainingclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.UUIDField(editable=False, help_text='课程安排唯一标识符', primary_key=True, serialize=False, verbose_name='课程ID')),
                ('course_name', models.CharField(help_text='请输入课程名称，如"海上救生设备操作"', max_length=200, verbose_name='课程名称')),
                ('course_type', models.CharField(choices=[('theory', '理论课'), ('practical', '实操课'), ('exam', '考试'), ('assessment', '评估')], help_text='theory=理论课, practical=实操课, exam=考试, assessment=评估', max_length=20, verbose_name='课程类型')),
                ('teacher', models.CharField(help_text='授课教师姓名', max_length=100, verbose_name='授课教师')),
                ('teacher_contact', models.CharField(blank=True, help_text='授课教师联系方式', max_length=100, verbose_name='教师联系方式')),
                ('date', models.DateField(help_text='课程安排的日期', verbose_name='课程日期')),
                ('session', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午'), ('evening', '晚上'), ('full_day', '全天')], help_text='morning=上午, afternoon=下午, evening=晚上, full_day=全天', max_length=10, verbose_name='场次')),
                ('start_time', models.TimeField(help_text='课程开始时间', verbose_name='开始时间')),
                ('end_time', models.TimeField(help_text='课程结束时间', verbose_name='结束时间')),
                ('location', models.CharField(help_text='上课地点/教室，如"A101教室"或"实操场地1"', max_length=200, verbose_name='上课地点')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='本课程最大容纳人数，不填则跟随班级设置', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='最大人数')),
                ('credit_hours', models.DecimalField(decimal_places=1, default=0, help_text='本课程对应的学分或学时数', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='学分/学时')),
                ('description', models.TextField(blank=True, help_text='课程的详细说明', verbose_name='课程简介')),
                ('materials', models.TextField(blank=True, help_text='本课程需要的教材或材料清单', verbose_name='所需教材/材料')),
                ('prerequisite', models.CharField(blank=True, help_text='本课程的先修课程要求', max_length=500, verbose_name='先修课程')),
                ('remark', models.CharField(blank=True, help_text='特殊情况说明', max_length=500, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间', verbose_name='更新时间')),
                ('training_class', models.ForeignKey(help_text='课程所属的培训班', on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='training_app.trainingclass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '课程安排',
                'verbose_name_plural': '课程安排列表',
                'db_table': 'course_schedule',
                'ordering': ['date', 'start_time', 'session'],
                'indexes': [models.Index(fields=['training_class', 'date'], name='course_sche_trainin_9b8b11_idx'), models.Index(fields=['date'], name='course_sche_date_e24c98_idx'), models.Index(fields=['course_type'], name='course_sche_course__6a0b9a_idx'), models.Index(fields=['teacher'], name='course_sche_teacher_8c8272_idx'), models.Index(fields=['-date'], name='course_sche_date_6a0b49_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingClassStudent',
            fields=[
                ('id', models.BigAutoField(help_text='关联记录唯一标识符', primary_key=True, serialize=False, verbose_name='记录ID')),
                ('enrollment_status', models.CharField(choices=[('pending', '报名待审'), ('first_review', '资格初审'), ('second_review', '复审'), ('confirmed', '已确认'), ('rejected', '已拒绝')], db_index=True, default='pending', help_text='学员报名审核状态', max_length=20, verbose_name='报名状态')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='学员出勤率，范围 0.00 ~ 999.99，单位：%', max_digits=5, verbose_name='出勤率')),
                ('certificate_issued', models.BooleanField(default=False, help_text='是否已发放培训证书', verbose_name='已发证')),
                ('certificate_no', models.CharField(blank=True, help_text='发放证书的编号，未发放时为空', max_length=64, verbose_name='证书编号')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='自动记录', verbose_name='报名时间')),
                ('student', models.ForeignKey(help_text='选择报名的学员', on_delete=django.db.models.deletion.CASCADE, to='student_app.student', verbose_name='学员')),
                ('training_class', models.ForeignKey(help_text='选择报名的培训班', on_delete=django.db.models.deletion.CASCADE, to='training_app.trainingclass', verbose_name='培训班')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录列表',
                'ordering': ['-enrolled_at'],
                'unique_together': {('training_class', 'student')},
            },
        ),
    ]
