# Generated by Django 5.0 on 2026-04-23 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
        ('student_app', '0001_initial'),
        ('training_app', '0003_courseschedule_trainingclassstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='证书唯一标识符', primary_key=True, serialize=False, verbose_name='证书ID')),
                ('certificate_no', models.CharField(db_index=True, help_text='请输入唯一的证书编号', max_length=64, unique=True, verbose_name='证书编号')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='证书发放时间，系统自动记录', verbose_name='发放时间')),
                ('validity_start', models.DateField(help_text='证书有效期开始日期', verbose_name='有效期开始')),
                ('validity_end', models.DateField(help_text='证书有效期结束日期', verbose_name='有效期结束')),
                ('status', models.CharField(choices=[('issued', '已发放'), ('revoked', '已撤销'), ('lost', '已挂失')], db_index=True, default='issued', help_text='issued=已发放, revoked=已撤销, lost=已挂失', max_length=20, verbose_name='证书状态')),
                ('idem_key', models.CharField(db_index=True, help_text='用于防止重复发放，由学员ID+培训班ID+培训类型ID组合生成', max_length=128, unique=True, verbose_name='幂等键')),
                ('revoke_reason', models.CharField(blank=True, help_text='撤销或挂失证书时的原因说明', max_length=500, verbose_name='撤销/挂失原因')),
                ('remark', models.CharField(blank=True, help_text='特殊情况说明', max_length=500, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间', verbose_name='更新时间')),
                ('issued_by', models.ForeignKey(blank=True, help_text='发放证书的操作人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='organization_app.personnel', verbose_name='发证人')),
                ('student', models.ForeignKey(help_text='获得证书的学员', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student_app.student', verbose_name='学员')),
                ('training_class', models.ForeignKey(help_text='完成培训的培训班', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='training_app.trainingclass', verbose_name='所属培训班')),
                ('training_type', models.ForeignKey(help_text='证书对应的培训类型', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='training_app.trainingtype', verbose_name='培训类型')),
            ],
            options={
                'verbose_name': '培训证书',
                'verbose_name_plural': '培训证书列表',
                'db_table': 'certificate',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['student', 'training_class'], name='certificate_student_3e770b_idx'), models.Index(fields=['training_type'], name='certificate_trainin_58c99b_idx'), models.Index(fields=['status'], name='certificate_status_a76d5c_idx'), models.Index(fields=['validity_end'], name='certificate_validit_256e8e_idx'), models.Index(fields=['-issued_at'], name='certificate_issued__0b6fad_idx')],
            },
        ),
    ]
