# Generated by Django 5.0 on 2026-04-23 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        ('training_app', '0003_courseschedule_trainingclassstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='考勤记录唯一标识符', primary_key=True, serialize=False, verbose_name='考勤记录ID')),
                ('date', models.DateField(help_text='进行考勤的日期', verbose_name='考勤日期')),
                ('session', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午')], help_text='上午或下午', max_length=10, verbose_name='场次')),
                ('check_in', models.DateTimeField(blank=True, help_text='学员签到时间', null=True, verbose_name='签到时间')),
                ('check_out', models.DateTimeField(blank=True, help_text='学员签退时间', null=True, verbose_name='签退时间')),
                ('status', models.CharField(choices=[('present', '正常签到'), ('late', '迟到'), ('absent', '缺勤'), ('leave', '请假')], db_index=True, default='absent', help_text='present=正常签到, late=迟到, absent=缺勤, leave=请假', max_length=20, verbose_name='考勤状态')),
                ('remark', models.CharField(blank=True, help_text='特殊情况说明，如迟到原因等', max_length=500, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间', verbose_name='更新时间')),
                ('course_schedule', models.ForeignKey(blank=True, help_text='关联的课程安排，可为空（如随机考勤）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='training_app.courseschedule', verbose_name='关联课程')),
                ('student', models.ForeignKey(help_text='进行考勤的学员', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_app.student', verbose_name='学员')),
                ('training_class', models.ForeignKey(help_text='学员所属的培训班', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='training_app.trainingclass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录列表',
                'db_table': 'attendance_record',
                'ordering': ['-date', '-session', 'student'],
                'indexes': [models.Index(fields=['training_class', 'date', 'session'], name='attendance__trainin_3d14ee_idx'), models.Index(fields=['student', 'date'], name='attendance__student_18d338_idx'), models.Index(fields=['status'], name='attendance__status_40d6e1_idx'), models.Index(fields=['-date'], name='attendance__date_343539_idx')],
                'unique_together': {('training_class', 'student', 'date', 'session')},
            },
        ),
    ]
