# Generated by Django 5.0 on 2026-04-21 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(help_text='组织唯一标识符', primary_key=True, serialize=False, verbose_name='组织ID')),
                ('name', models.CharField(help_text='请输入组织全称（如"华东航运公司"）', max_length=100, verbose_name='组织名称')),
                ('org_type', models.CharField(choices=[('company', '公司'), ('department', '部门'), ('office', '办公室')], help_text='选择组织的类型：公司、部门或办公室', max_length=20, verbose_name='组织类型')),
                ('level', models.PositiveIntegerField(default=0, help_text='自动计算，用于前端展示树形结构深度', verbose_name='层级深度')),
                ('path', models.CharField(db_index=True, help_text='自动生成，格式如 /company1/dept2/office3', max_length=500, verbose_name='组织路径')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记，True 表示已删除', verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='自动记录最后修改时间', verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, help_text='选择上级组织，顶级组织无需选择', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization_app.organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织列表',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(help_text='人员唯一标识符', primary_key=True, serialize=False, verbose_name='人员ID')),
                ('name', models.CharField(help_text='请输入人员真实姓名', max_length=100, verbose_name='姓名')),
                ('id_card', models.CharField(help_text='格式为18位身份证号，最后一位可为 X', max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone', models.CharField(help_text='请输入11位手机号', max_length=20, verbose_name='手机号码')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记，True 表示已删除', verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='自动记录最后修改时间', verbose_name='更新时间')),
                ('organization', models.ForeignKey(help_text='选择人员所属的组织', on_delete=django.db.models.deletion.PROTECT, related_name='personnels', to='organization_app.organization', verbose_name='所属组织')),
                ('user', models.OneToOneField(help_text='关联系统用户，删除用户时人员记录一并删除', on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员列表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(help_text='职务唯一标识符', primary_key=True, serialize=False, verbose_name='职务ID')),
                ('name', models.CharField(help_text='请输入职务名称，如"船长"、"大副"', max_length=50, verbose_name='职务名称')),
                ('code', models.CharField(help_text='请输入唯一的职务编码，如"CAPTAIN"、"FIRST_MATE"', max_length=20, unique=True, verbose_name='职务编码')),
                ('permissions', models.JSONField(default=list, help_text='JSON格式的权限标识列表，如["training.create", "attendance.view"]', verbose_name='权限列表')),
                ('is_concurrentable', models.BooleanField(default=True, help_text='是否允许人员兼任此职务', verbose_name='允许兼职')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='自动更新', verbose_name='更新时间')),
                ('organization', models.ForeignKey(help_text='选择职务所属的组织', on_delete=django.db.models.deletion.CASCADE, to='organization_app.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '职务',
                'verbose_name_plural': '职务列表',
                'ordering': ['organization__path', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelPosition',
            fields=[
                ('id', models.BigAutoField(help_text='关联记录唯一标识符', primary_key=True, serialize=False, verbose_name='记录ID')),
                ('is_primary', models.BooleanField(default=False, help_text='是否为主职务（一个人只能有一个主职务）', verbose_name='主职务')),
                ('is_active', models.BooleanField(default=True, help_text='是否生效', verbose_name='生效中')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='自动记录', verbose_name='创建时间')),
                ('personnel', models.ForeignKey(help_text='选择人员', on_delete=django.db.models.deletion.CASCADE, to='organization_app.personnel', verbose_name='人员')),
                ('position', models.ForeignKey(help_text='选择职务', on_delete=django.db.models.deletion.CASCADE, to='organization_app.position', verbose_name='职务')),
            ],
            options={
                'verbose_name': '人员职务',
                'verbose_name_plural': '人员职务列表',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('personnel', 'position')},
            },
        ),
    ]
