# Generated by Django 5.0 on 2026-04-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='permissions',
        ),
        migrations.AddField(
            model_name='position',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='positions', to='auth.permission', verbose_name='权限列表'),
        ),
    ]
